// Code generated by goctl. DO NOT EDIT.
// Source: sms.proto

package server

import (
	"context"

	"simple_mall_new/rpc/sms/internal/logic"
	"simple_mall_new/rpc/sms/internal/svc"
	"simple_mall_new/rpc/sms/sms"
)

type SmsServer struct {
	svcCtx *svc.ServiceContext
	sms.UnimplementedSmsServer
}

func NewSmsServer(svcCtx *svc.ServiceContext) *SmsServer {
	return &SmsServer{
		svcCtx: svcCtx,
	}
}

// 添加｜｜更新广告
func (s *SmsServer) SaveOrUpdateHomeAdvertise(ctx context.Context, in *sms.SaveOrUpdateHomeAdvertiseReq) (*sms.SaveOrUpdateHomeAdvertiseResp, error) {
	l := logic.NewSaveOrUpdateHomeAdvertiseLogic(ctx, s.svcCtx)
	return l.SaveOrUpdateHomeAdvertise(in)
}

// 广告列表
func (s *SmsServer) HomeAdvertiseList(ctx context.Context, in *sms.HomeAdvertiseListReq) (*sms.HomeAdvertiseListResp, error) {
	l := logic.NewHomeAdvertiseListLogic(ctx, s.svcCtx)
	return l.HomeAdvertiseList(in)
}

// 删除广告
func (s *SmsServer) HomeAdvertiseDelete(ctx context.Context, in *sms.HomeAdvertiseDeleteReq) (*sms.HomeAdvertiseDeleteResp, error) {
	l := logic.NewHomeAdvertiseDeleteLogic(ctx, s.svcCtx)
	return l.HomeAdvertiseDelete(in)
}

// 添加｜｜更新优惠券
func (s *SmsServer) SaveOrUpdateCoupon(ctx context.Context, in *sms.SaveOrUpdateCouponReq) (*sms.SaveOrUpdateCouponResp, error) {
	l := logic.NewSaveOrUpdateCouponLogic(ctx, s.svcCtx)
	return l.SaveOrUpdateCoupon(in)
}

// 删除优惠券
func (s *SmsServer) CouponDelete(ctx context.Context, in *sms.CouponDeleteReq) (*sms.CouponDeleteResp, error) {
	l := logic.NewCouponDeleteLogic(ctx, s.svcCtx)
	return l.CouponDelete(in)
}

// 优惠券列表
func (s *SmsServer) CouponList(ctx context.Context, in *sms.CouponListReq) (*sms.CouponListResp, error) {
	l := logic.NewCouponListLogic(ctx, s.svcCtx)
	return l.CouponList(in)
}
