// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	sysuser "simple_mall_new/api/internal/handler/sys/user"
	"simple_mall_new/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: sysuser.UserLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/sys/user"),
	)
}
