// Code generated by goctl. DO NOT EDIT.
// Source: sms.proto

package smsclient

import (
	"context"

	"simple_mall_new/rpc/sms/sms"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CouponDeleteReq               = sms.CouponDeleteReq
	CouponDeleteResp              = sms.CouponDeleteResp
	CouponListData                = sms.CouponListData
	CouponListReq                 = sms.CouponListReq
	CouponListResp                = sms.CouponListResp
	HomeAdvertiseDeleteReq        = sms.HomeAdvertiseDeleteReq
	HomeAdvertiseDeleteResp       = sms.HomeAdvertiseDeleteResp
	HomeAdvertiseListData         = sms.HomeAdvertiseListData
	HomeAdvertiseListReq          = sms.HomeAdvertiseListReq
	HomeAdvertiseListResp         = sms.HomeAdvertiseListResp
	SaveOrUpdateCouponReq         = sms.SaveOrUpdateCouponReq
	SaveOrUpdateCouponResp        = sms.SaveOrUpdateCouponResp
	SaveOrUpdateHomeAdvertiseReq  = sms.SaveOrUpdateHomeAdvertiseReq
	SaveOrUpdateHomeAdvertiseResp = sms.SaveOrUpdateHomeAdvertiseResp

	Sms interface {
		// 添加｜｜更新广告
		SaveOrUpdateHomeAdvertise(ctx context.Context, in *SaveOrUpdateHomeAdvertiseReq, opts ...grpc.CallOption) (*SaveOrUpdateHomeAdvertiseResp, error)
		// 广告列表
		HomeAdvertiseList(ctx context.Context, in *HomeAdvertiseListReq, opts ...grpc.CallOption) (*HomeAdvertiseListResp, error)
		// 删除广告
		HomeAdvertiseDelete(ctx context.Context, in *HomeAdvertiseDeleteReq, opts ...grpc.CallOption) (*HomeAdvertiseDeleteResp, error)
		// 添加｜｜更新优惠券
		SaveOrUpdateCoupon(ctx context.Context, in *SaveOrUpdateCouponReq, opts ...grpc.CallOption) (*SaveOrUpdateCouponResp, error)
		// 删除优惠券
		CouponDelete(ctx context.Context, in *CouponDeleteReq, opts ...grpc.CallOption) (*CouponDeleteResp, error)
		// 优惠券列表
		CouponList(ctx context.Context, in *CouponListReq, opts ...grpc.CallOption) (*CouponListResp, error)
	}

	defaultSms struct {
		cli zrpc.Client
	}
)

func NewSms(cli zrpc.Client) Sms {
	return &defaultSms{
		cli: cli,
	}
}

// 添加｜｜更新广告
func (m *defaultSms) SaveOrUpdateHomeAdvertise(ctx context.Context, in *SaveOrUpdateHomeAdvertiseReq, opts ...grpc.CallOption) (*SaveOrUpdateHomeAdvertiseResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.SaveOrUpdateHomeAdvertise(ctx, in, opts...)
}

// 广告列表
func (m *defaultSms) HomeAdvertiseList(ctx context.Context, in *HomeAdvertiseListReq, opts ...grpc.CallOption) (*HomeAdvertiseListResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.HomeAdvertiseList(ctx, in, opts...)
}

// 删除广告
func (m *defaultSms) HomeAdvertiseDelete(ctx context.Context, in *HomeAdvertiseDeleteReq, opts ...grpc.CallOption) (*HomeAdvertiseDeleteResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.HomeAdvertiseDelete(ctx, in, opts...)
}

// 添加｜｜更新优惠券
func (m *defaultSms) SaveOrUpdateCoupon(ctx context.Context, in *SaveOrUpdateCouponReq, opts ...grpc.CallOption) (*SaveOrUpdateCouponResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.SaveOrUpdateCoupon(ctx, in, opts...)
}

// 删除优惠券
func (m *defaultSms) CouponDelete(ctx context.Context, in *CouponDeleteReq, opts ...grpc.CallOption) (*CouponDeleteResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.CouponDelete(ctx, in, opts...)
}

// 优惠券列表
func (m *defaultSms) CouponList(ctx context.Context, in *CouponListReq, opts ...grpc.CallOption) (*CouponListResp, error) {
	client := sms.NewSmsClient(m.cli.Conn())
	return client.CouponList(ctx, in, opts...)
}
