// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: pms.proto

package pms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Pms_SaveOrUpdateCategory_FullMethodName = "/pms.Pms/SaveOrUpdateCategory"
	Pms_CategoryList_FullMethodName         = "/pms.Pms/CategoryList"
	Pms_CategoryDelete_FullMethodName       = "/pms.Pms/CategoryDelete"
	Pms_MerchantsApplyAdd_FullMethodName    = "/pms.Pms/MerchantsApplyAdd"
	Pms_MerchantsApplyList_FullMethodName   = "/pms.Pms/MerchantsApplyList"
	Pms_MerchantsApplyUpdate_FullMethodName = "/pms.Pms/MerchantsApplyUpdate"
	Pms_MerchantsApplyDelete_FullMethodName = "/pms.Pms/MerchantsApplyDelete"
	Pms_MerchantsList_FullMethodName        = "/pms.Pms/MerchantsList"
	Pms_MerchantsUpdate_FullMethodName      = "/pms.Pms/MerchantsUpdate"
	Pms_MerchantsDelete_FullMethodName      = "/pms.Pms/MerchantsDelete"
	Pms_MerchantsInfo_FullMethodName        = "/pms.Pms/MerchantsInfo"
	Pms_PlaceList_FullMethodName            = "/pms.Pms/PlaceList"
	Pms_PlaceUpdate_FullMethodName          = "/pms.Pms/PlaceUpdate"
	Pms_PlaceDelete_FullMethodName          = "/pms.Pms/PlaceDelete"
	Pms_PlaceInfo_FullMethodName            = "/pms.Pms/PlaceInfo"
	Pms_SaveOrUpdateProduct_FullMethodName  = "/pms.Pms/SaveOrUpdateProduct"
	Pms_ProductList_FullMethodName          = "/pms.Pms/ProductList"
	Pms_ProductDelete_FullMethodName        = "/pms.Pms/ProductDelete"
	Pms_ProductInfo_FullMethodName          = "/pms.Pms/ProductInfo"
	Pms_SkuList_FullMethodName              = "/pms.Pms/SkuList"
	Pms_SkuUpdate_FullMethodName            = "/pms.Pms/SkuUpdate"
)

// PmsClient is the client API for Pms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PmsClient interface {
	// 添加||更新分类
	SaveOrUpdateCategory(ctx context.Context, in *SaveOrUpdateCategoryReq, opts ...grpc.CallOption) (*SaveOrUpdateCategoryResp, error)
	// 分类列表
	CategoryList(ctx context.Context, in *CategoryListReq, opts ...grpc.CallOption) (*CategoryListResp, error)
	// 删除分类
	CategoryDelete(ctx context.Context, in *CategoryDeleteReq, opts ...grpc.CallOption) (*CategoryDeleteResp, error)
	// 入驻申请
	MerchantsApplyAdd(ctx context.Context, in *MerchantsApplyAddReq, opts ...grpc.CallOption) (*MerchantsApplyAddResp, error)
	// 入驻申请列表
	MerchantsApplyList(ctx context.Context, in *MerchantsApplyListReq, opts ...grpc.CallOption) (*MerchantsApplyListResp, error)
	// 审核入驻申请
	MerchantsApplyUpdate(ctx context.Context, in *MerchantsApplyUpdateReq, opts ...grpc.CallOption) (*MerchantsApplyUpdateResp, error)
	// 删除入驻申请
	MerchantsApplyDelete(ctx context.Context, in *MerchantsApplyDeleteReq, opts ...grpc.CallOption) (*MerchantsApplyDeleteResp, error)
	// 商家列表
	MerchantsList(ctx context.Context, in *MerchantsListReq, opts ...grpc.CallOption) (*MerchantsListResp, error)
	// 更新商家
	MerchantsUpdate(ctx context.Context, in *MerchantsUpdateReq, opts ...grpc.CallOption) (*MerchantsUpdateResp, error)
	// 删除商家
	MerchantsDelete(ctx context.Context, in *MerchantsDeleteReq, opts ...grpc.CallOption) (*MerchantsDeleteResp, error)
	// 商家详情
	MerchantsInfo(ctx context.Context, in *MerchantsInfoReq, opts ...grpc.CallOption) (*MerchantsInfoResp, error)
	// 自提点列表
	PlaceList(ctx context.Context, in *PlaceListReq, opts ...grpc.CallOption) (*PlaceListResp, error)
	// 更新自提点
	PlaceUpdate(ctx context.Context, in *PlaceUpdateReq, opts ...grpc.CallOption) (*PlaceUpdateResp, error)
	// 删除自提点
	PlaceDelete(ctx context.Context, in *PlaceDeleteReq, opts ...grpc.CallOption) (*PlaceDeleteResp, error)
	// 自提点详情
	PlaceInfo(ctx context.Context, in *PlaceInfoReq, opts ...grpc.CallOption) (*PlaceInfoResp, error)
	// 添加||更新商品
	SaveOrUpdateProduct(ctx context.Context, in *SaveOrUpdateProductReq, opts ...grpc.CallOption) (*SaveOrUpdateProductResp, error)
	// 商品列表
	ProductList(ctx context.Context, in *ProductListReq, opts ...grpc.CallOption) (*ProductListResp, error)
	// 删除商品
	ProductDelete(ctx context.Context, in *ProductDeleteReq, opts ...grpc.CallOption) (*ProductDeleteResp, error)
	// 查询商品详情
	ProductInfo(ctx context.Context, in *ProductInfoReq, opts ...grpc.CallOption) (*ProductInfoResp, error)
	// Sku列表
	SkuList(ctx context.Context, in *SkuListReq, opts ...grpc.CallOption) (*SkuListResp, error)
	// 更新Sku
	SkuUpdate(ctx context.Context, in *SkuUpdateReq, opts ...grpc.CallOption) (*SkuUpdateResp, error)
}

type pmsClient struct {
	cc grpc.ClientConnInterface
}

func NewPmsClient(cc grpc.ClientConnInterface) PmsClient {
	return &pmsClient{cc}
}

func (c *pmsClient) SaveOrUpdateCategory(ctx context.Context, in *SaveOrUpdateCategoryReq, opts ...grpc.CallOption) (*SaveOrUpdateCategoryResp, error) {
	out := new(SaveOrUpdateCategoryResp)
	err := c.cc.Invoke(ctx, Pms_SaveOrUpdateCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) CategoryList(ctx context.Context, in *CategoryListReq, opts ...grpc.CallOption) (*CategoryListResp, error) {
	out := new(CategoryListResp)
	err := c.cc.Invoke(ctx, Pms_CategoryList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) CategoryDelete(ctx context.Context, in *CategoryDeleteReq, opts ...grpc.CallOption) (*CategoryDeleteResp, error) {
	out := new(CategoryDeleteResp)
	err := c.cc.Invoke(ctx, Pms_CategoryDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) MerchantsApplyAdd(ctx context.Context, in *MerchantsApplyAddReq, opts ...grpc.CallOption) (*MerchantsApplyAddResp, error) {
	out := new(MerchantsApplyAddResp)
	err := c.cc.Invoke(ctx, Pms_MerchantsApplyAdd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) MerchantsApplyList(ctx context.Context, in *MerchantsApplyListReq, opts ...grpc.CallOption) (*MerchantsApplyListResp, error) {
	out := new(MerchantsApplyListResp)
	err := c.cc.Invoke(ctx, Pms_MerchantsApplyList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) MerchantsApplyUpdate(ctx context.Context, in *MerchantsApplyUpdateReq, opts ...grpc.CallOption) (*MerchantsApplyUpdateResp, error) {
	out := new(MerchantsApplyUpdateResp)
	err := c.cc.Invoke(ctx, Pms_MerchantsApplyUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) MerchantsApplyDelete(ctx context.Context, in *MerchantsApplyDeleteReq, opts ...grpc.CallOption) (*MerchantsApplyDeleteResp, error) {
	out := new(MerchantsApplyDeleteResp)
	err := c.cc.Invoke(ctx, Pms_MerchantsApplyDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) MerchantsList(ctx context.Context, in *MerchantsListReq, opts ...grpc.CallOption) (*MerchantsListResp, error) {
	out := new(MerchantsListResp)
	err := c.cc.Invoke(ctx, Pms_MerchantsList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) MerchantsUpdate(ctx context.Context, in *MerchantsUpdateReq, opts ...grpc.CallOption) (*MerchantsUpdateResp, error) {
	out := new(MerchantsUpdateResp)
	err := c.cc.Invoke(ctx, Pms_MerchantsUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) MerchantsDelete(ctx context.Context, in *MerchantsDeleteReq, opts ...grpc.CallOption) (*MerchantsDeleteResp, error) {
	out := new(MerchantsDeleteResp)
	err := c.cc.Invoke(ctx, Pms_MerchantsDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) MerchantsInfo(ctx context.Context, in *MerchantsInfoReq, opts ...grpc.CallOption) (*MerchantsInfoResp, error) {
	out := new(MerchantsInfoResp)
	err := c.cc.Invoke(ctx, Pms_MerchantsInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) PlaceList(ctx context.Context, in *PlaceListReq, opts ...grpc.CallOption) (*PlaceListResp, error) {
	out := new(PlaceListResp)
	err := c.cc.Invoke(ctx, Pms_PlaceList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) PlaceUpdate(ctx context.Context, in *PlaceUpdateReq, opts ...grpc.CallOption) (*PlaceUpdateResp, error) {
	out := new(PlaceUpdateResp)
	err := c.cc.Invoke(ctx, Pms_PlaceUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) PlaceDelete(ctx context.Context, in *PlaceDeleteReq, opts ...grpc.CallOption) (*PlaceDeleteResp, error) {
	out := new(PlaceDeleteResp)
	err := c.cc.Invoke(ctx, Pms_PlaceDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) PlaceInfo(ctx context.Context, in *PlaceInfoReq, opts ...grpc.CallOption) (*PlaceInfoResp, error) {
	out := new(PlaceInfoResp)
	err := c.cc.Invoke(ctx, Pms_PlaceInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) SaveOrUpdateProduct(ctx context.Context, in *SaveOrUpdateProductReq, opts ...grpc.CallOption) (*SaveOrUpdateProductResp, error) {
	out := new(SaveOrUpdateProductResp)
	err := c.cc.Invoke(ctx, Pms_SaveOrUpdateProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) ProductList(ctx context.Context, in *ProductListReq, opts ...grpc.CallOption) (*ProductListResp, error) {
	out := new(ProductListResp)
	err := c.cc.Invoke(ctx, Pms_ProductList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) ProductDelete(ctx context.Context, in *ProductDeleteReq, opts ...grpc.CallOption) (*ProductDeleteResp, error) {
	out := new(ProductDeleteResp)
	err := c.cc.Invoke(ctx, Pms_ProductDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) ProductInfo(ctx context.Context, in *ProductInfoReq, opts ...grpc.CallOption) (*ProductInfoResp, error) {
	out := new(ProductInfoResp)
	err := c.cc.Invoke(ctx, Pms_ProductInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) SkuList(ctx context.Context, in *SkuListReq, opts ...grpc.CallOption) (*SkuListResp, error) {
	out := new(SkuListResp)
	err := c.cc.Invoke(ctx, Pms_SkuList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmsClient) SkuUpdate(ctx context.Context, in *SkuUpdateReq, opts ...grpc.CallOption) (*SkuUpdateResp, error) {
	out := new(SkuUpdateResp)
	err := c.cc.Invoke(ctx, Pms_SkuUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PmsServer is the server API for Pms service.
// All implementations must embed UnimplementedPmsServer
// for forward compatibility
type PmsServer interface {
	// 添加||更新分类
	SaveOrUpdateCategory(context.Context, *SaveOrUpdateCategoryReq) (*SaveOrUpdateCategoryResp, error)
	// 分类列表
	CategoryList(context.Context, *CategoryListReq) (*CategoryListResp, error)
	// 删除分类
	CategoryDelete(context.Context, *CategoryDeleteReq) (*CategoryDeleteResp, error)
	// 入驻申请
	MerchantsApplyAdd(context.Context, *MerchantsApplyAddReq) (*MerchantsApplyAddResp, error)
	// 入驻申请列表
	MerchantsApplyList(context.Context, *MerchantsApplyListReq) (*MerchantsApplyListResp, error)
	// 审核入驻申请
	MerchantsApplyUpdate(context.Context, *MerchantsApplyUpdateReq) (*MerchantsApplyUpdateResp, error)
	// 删除入驻申请
	MerchantsApplyDelete(context.Context, *MerchantsApplyDeleteReq) (*MerchantsApplyDeleteResp, error)
	// 商家列表
	MerchantsList(context.Context, *MerchantsListReq) (*MerchantsListResp, error)
	// 更新商家
	MerchantsUpdate(context.Context, *MerchantsUpdateReq) (*MerchantsUpdateResp, error)
	// 删除商家
	MerchantsDelete(context.Context, *MerchantsDeleteReq) (*MerchantsDeleteResp, error)
	// 商家详情
	MerchantsInfo(context.Context, *MerchantsInfoReq) (*MerchantsInfoResp, error)
	// 自提点列表
	PlaceList(context.Context, *PlaceListReq) (*PlaceListResp, error)
	// 更新自提点
	PlaceUpdate(context.Context, *PlaceUpdateReq) (*PlaceUpdateResp, error)
	// 删除自提点
	PlaceDelete(context.Context, *PlaceDeleteReq) (*PlaceDeleteResp, error)
	// 自提点详情
	PlaceInfo(context.Context, *PlaceInfoReq) (*PlaceInfoResp, error)
	// 添加||更新商品
	SaveOrUpdateProduct(context.Context, *SaveOrUpdateProductReq) (*SaveOrUpdateProductResp, error)
	// 商品列表
	ProductList(context.Context, *ProductListReq) (*ProductListResp, error)
	// 删除商品
	ProductDelete(context.Context, *ProductDeleteReq) (*ProductDeleteResp, error)
	// 查询商品详情
	ProductInfo(context.Context, *ProductInfoReq) (*ProductInfoResp, error)
	// Sku列表
	SkuList(context.Context, *SkuListReq) (*SkuListResp, error)
	// 更新Sku
	SkuUpdate(context.Context, *SkuUpdateReq) (*SkuUpdateResp, error)
	mustEmbedUnimplementedPmsServer()
}

// UnimplementedPmsServer must be embedded to have forward compatible implementations.
type UnimplementedPmsServer struct {
}

func (UnimplementedPmsServer) SaveOrUpdateCategory(context.Context, *SaveOrUpdateCategoryReq) (*SaveOrUpdateCategoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveOrUpdateCategory not implemented")
}
func (UnimplementedPmsServer) CategoryList(context.Context, *CategoryListReq) (*CategoryListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategoryList not implemented")
}
func (UnimplementedPmsServer) CategoryDelete(context.Context, *CategoryDeleteReq) (*CategoryDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategoryDelete not implemented")
}
func (UnimplementedPmsServer) MerchantsApplyAdd(context.Context, *MerchantsApplyAddReq) (*MerchantsApplyAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsApplyAdd not implemented")
}
func (UnimplementedPmsServer) MerchantsApplyList(context.Context, *MerchantsApplyListReq) (*MerchantsApplyListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsApplyList not implemented")
}
func (UnimplementedPmsServer) MerchantsApplyUpdate(context.Context, *MerchantsApplyUpdateReq) (*MerchantsApplyUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsApplyUpdate not implemented")
}
func (UnimplementedPmsServer) MerchantsApplyDelete(context.Context, *MerchantsApplyDeleteReq) (*MerchantsApplyDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsApplyDelete not implemented")
}
func (UnimplementedPmsServer) MerchantsList(context.Context, *MerchantsListReq) (*MerchantsListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsList not implemented")
}
func (UnimplementedPmsServer) MerchantsUpdate(context.Context, *MerchantsUpdateReq) (*MerchantsUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsUpdate not implemented")
}
func (UnimplementedPmsServer) MerchantsDelete(context.Context, *MerchantsDeleteReq) (*MerchantsDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsDelete not implemented")
}
func (UnimplementedPmsServer) MerchantsInfo(context.Context, *MerchantsInfoReq) (*MerchantsInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantsInfo not implemented")
}
func (UnimplementedPmsServer) PlaceList(context.Context, *PlaceListReq) (*PlaceListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceList not implemented")
}
func (UnimplementedPmsServer) PlaceUpdate(context.Context, *PlaceUpdateReq) (*PlaceUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceUpdate not implemented")
}
func (UnimplementedPmsServer) PlaceDelete(context.Context, *PlaceDeleteReq) (*PlaceDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceDelete not implemented")
}
func (UnimplementedPmsServer) PlaceInfo(context.Context, *PlaceInfoReq) (*PlaceInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceInfo not implemented")
}
func (UnimplementedPmsServer) SaveOrUpdateProduct(context.Context, *SaveOrUpdateProductReq) (*SaveOrUpdateProductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveOrUpdateProduct not implemented")
}
func (UnimplementedPmsServer) ProductList(context.Context, *ProductListReq) (*ProductListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductList not implemented")
}
func (UnimplementedPmsServer) ProductDelete(context.Context, *ProductDeleteReq) (*ProductDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductDelete not implemented")
}
func (UnimplementedPmsServer) ProductInfo(context.Context, *ProductInfoReq) (*ProductInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductInfo not implemented")
}
func (UnimplementedPmsServer) SkuList(context.Context, *SkuListReq) (*SkuListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SkuList not implemented")
}
func (UnimplementedPmsServer) SkuUpdate(context.Context, *SkuUpdateReq) (*SkuUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SkuUpdate not implemented")
}
func (UnimplementedPmsServer) mustEmbedUnimplementedPmsServer() {}

// UnsafePmsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PmsServer will
// result in compilation errors.
type UnsafePmsServer interface {
	mustEmbedUnimplementedPmsServer()
}

func RegisterPmsServer(s grpc.ServiceRegistrar, srv PmsServer) {
	s.RegisterService(&Pms_ServiceDesc, srv)
}

func _Pms_SaveOrUpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveOrUpdateCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).SaveOrUpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_SaveOrUpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).SaveOrUpdateCategory(ctx, req.(*SaveOrUpdateCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_CategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).CategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_CategoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).CategoryList(ctx, req.(*CategoryListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_CategoryDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).CategoryDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_CategoryDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).CategoryDelete(ctx, req.(*CategoryDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_MerchantsApplyAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsApplyAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).MerchantsApplyAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_MerchantsApplyAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).MerchantsApplyAdd(ctx, req.(*MerchantsApplyAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_MerchantsApplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsApplyListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).MerchantsApplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_MerchantsApplyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).MerchantsApplyList(ctx, req.(*MerchantsApplyListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_MerchantsApplyUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsApplyUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).MerchantsApplyUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_MerchantsApplyUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).MerchantsApplyUpdate(ctx, req.(*MerchantsApplyUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_MerchantsApplyDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsApplyDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).MerchantsApplyDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_MerchantsApplyDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).MerchantsApplyDelete(ctx, req.(*MerchantsApplyDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_MerchantsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).MerchantsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_MerchantsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).MerchantsList(ctx, req.(*MerchantsListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_MerchantsUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).MerchantsUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_MerchantsUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).MerchantsUpdate(ctx, req.(*MerchantsUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_MerchantsDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).MerchantsDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_MerchantsDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).MerchantsDelete(ctx, req.(*MerchantsDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_MerchantsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).MerchantsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_MerchantsInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).MerchantsInfo(ctx, req.(*MerchantsInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_PlaceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).PlaceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_PlaceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).PlaceList(ctx, req.(*PlaceListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_PlaceUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).PlaceUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_PlaceUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).PlaceUpdate(ctx, req.(*PlaceUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_PlaceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).PlaceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_PlaceDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).PlaceDelete(ctx, req.(*PlaceDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_PlaceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).PlaceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_PlaceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).PlaceInfo(ctx, req.(*PlaceInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_SaveOrUpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveOrUpdateProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).SaveOrUpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_SaveOrUpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).SaveOrUpdateProduct(ctx, req.(*SaveOrUpdateProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_ProductList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).ProductList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_ProductList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).ProductList(ctx, req.(*ProductListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_ProductDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).ProductDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_ProductDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).ProductDelete(ctx, req.(*ProductDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_ProductInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).ProductInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_ProductInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).ProductInfo(ctx, req.(*ProductInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_SkuList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkuListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).SkuList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_SkuList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).SkuList(ctx, req.(*SkuListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pms_SkuUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkuUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmsServer).SkuUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pms_SkuUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmsServer).SkuUpdate(ctx, req.(*SkuUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Pms_ServiceDesc is the grpc.ServiceDesc for Pms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pms.Pms",
	HandlerType: (*PmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveOrUpdateCategory",
			Handler:    _Pms_SaveOrUpdateCategory_Handler,
		},
		{
			MethodName: "CategoryList",
			Handler:    _Pms_CategoryList_Handler,
		},
		{
			MethodName: "CategoryDelete",
			Handler:    _Pms_CategoryDelete_Handler,
		},
		{
			MethodName: "MerchantsApplyAdd",
			Handler:    _Pms_MerchantsApplyAdd_Handler,
		},
		{
			MethodName: "MerchantsApplyList",
			Handler:    _Pms_MerchantsApplyList_Handler,
		},
		{
			MethodName: "MerchantsApplyUpdate",
			Handler:    _Pms_MerchantsApplyUpdate_Handler,
		},
		{
			MethodName: "MerchantsApplyDelete",
			Handler:    _Pms_MerchantsApplyDelete_Handler,
		},
		{
			MethodName: "MerchantsList",
			Handler:    _Pms_MerchantsList_Handler,
		},
		{
			MethodName: "MerchantsUpdate",
			Handler:    _Pms_MerchantsUpdate_Handler,
		},
		{
			MethodName: "MerchantsDelete",
			Handler:    _Pms_MerchantsDelete_Handler,
		},
		{
			MethodName: "MerchantsInfo",
			Handler:    _Pms_MerchantsInfo_Handler,
		},
		{
			MethodName: "PlaceList",
			Handler:    _Pms_PlaceList_Handler,
		},
		{
			MethodName: "PlaceUpdate",
			Handler:    _Pms_PlaceUpdate_Handler,
		},
		{
			MethodName: "PlaceDelete",
			Handler:    _Pms_PlaceDelete_Handler,
		},
		{
			MethodName: "PlaceInfo",
			Handler:    _Pms_PlaceInfo_Handler,
		},
		{
			MethodName: "SaveOrUpdateProduct",
			Handler:    _Pms_SaveOrUpdateProduct_Handler,
		},
		{
			MethodName: "ProductList",
			Handler:    _Pms_ProductList_Handler,
		},
		{
			MethodName: "ProductDelete",
			Handler:    _Pms_ProductDelete_Handler,
		},
		{
			MethodName: "ProductInfo",
			Handler:    _Pms_ProductInfo_Handler,
		},
		{
			MethodName: "SkuList",
			Handler:    _Pms_SkuList_Handler,
		},
		{
			MethodName: "SkuUpdate",
			Handler:    _Pms_SkuUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pms.proto",
}
