// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: sms.proto

package sms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加｜｜更新广告
type SaveOrUpdateHomeAdvertiseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pic    string `protobuf:"bytes,3,opt,name=pic,proto3" json:"pic,omitempty"`
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Sort   int64  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Url    string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Note   string `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *SaveOrUpdateHomeAdvertiseReq) Reset() {
	*x = SaveOrUpdateHomeAdvertiseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveOrUpdateHomeAdvertiseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOrUpdateHomeAdvertiseReq) ProtoMessage() {}

func (x *SaveOrUpdateHomeAdvertiseReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOrUpdateHomeAdvertiseReq.ProtoReflect.Descriptor instead.
func (*SaveOrUpdateHomeAdvertiseReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{0}
}

func (x *SaveOrUpdateHomeAdvertiseReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveOrUpdateHomeAdvertiseReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveOrUpdateHomeAdvertiseReq) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *SaveOrUpdateHomeAdvertiseReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SaveOrUpdateHomeAdvertiseReq) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *SaveOrUpdateHomeAdvertiseReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SaveOrUpdateHomeAdvertiseReq) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type SaveOrUpdateHomeAdvertiseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *SaveOrUpdateHomeAdvertiseResp) Reset() {
	*x = SaveOrUpdateHomeAdvertiseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveOrUpdateHomeAdvertiseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOrUpdateHomeAdvertiseResp) ProtoMessage() {}

func (x *SaveOrUpdateHomeAdvertiseResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOrUpdateHomeAdvertiseResp.ProtoReflect.Descriptor instead.
func (*SaveOrUpdateHomeAdvertiseResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{1}
}

func (x *SaveOrUpdateHomeAdvertiseResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 广告列表
type HomeAdvertiseListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNum  int64  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize int64  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status   string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *HomeAdvertiseListReq) Reset() {
	*x = HomeAdvertiseListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeAdvertiseListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeAdvertiseListReq) ProtoMessage() {}

func (x *HomeAdvertiseListReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeAdvertiseListReq.ProtoReflect.Descriptor instead.
func (*HomeAdvertiseListReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{2}
}

func (x *HomeAdvertiseListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *HomeAdvertiseListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *HomeAdvertiseListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HomeAdvertiseListReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HomeAdvertiseListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pic       string `protobuf:"bytes,3,opt,name=pic,proto3" json:"pic,omitempty"`
	Status    string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Sort      int64  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	Url       string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Note      string `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt string `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *HomeAdvertiseListData) Reset() {
	*x = HomeAdvertiseListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeAdvertiseListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeAdvertiseListData) ProtoMessage() {}

func (x *HomeAdvertiseListData) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeAdvertiseListData.ProtoReflect.Descriptor instead.
func (*HomeAdvertiseListData) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{3}
}

func (x *HomeAdvertiseListData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HomeAdvertiseListData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HomeAdvertiseListData) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *HomeAdvertiseListData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HomeAdvertiseListData) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *HomeAdvertiseListData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HomeAdvertiseListData) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *HomeAdvertiseListData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type HomeAdvertiseListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*HomeAdvertiseListData `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *HomeAdvertiseListResp) Reset() {
	*x = HomeAdvertiseListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeAdvertiseListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeAdvertiseListResp) ProtoMessage() {}

func (x *HomeAdvertiseListResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeAdvertiseListResp.ProtoReflect.Descriptor instead.
func (*HomeAdvertiseListResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{4}
}

func (x *HomeAdvertiseListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *HomeAdvertiseListResp) GetList() []*HomeAdvertiseListData {
	if x != nil {
		return x.List
	}
	return nil
}

// 删除广告
type HomeAdvertiseDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *HomeAdvertiseDeleteReq) Reset() {
	*x = HomeAdvertiseDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeAdvertiseDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeAdvertiseDeleteReq) ProtoMessage() {}

func (x *HomeAdvertiseDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeAdvertiseDeleteReq.ProtoReflect.Descriptor instead.
func (*HomeAdvertiseDeleteReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{5}
}

func (x *HomeAdvertiseDeleteReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type HomeAdvertiseDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *HomeAdvertiseDeleteResp) Reset() {
	*x = HomeAdvertiseDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HomeAdvertiseDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeAdvertiseDeleteResp) ProtoMessage() {}

func (x *HomeAdvertiseDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeAdvertiseDeleteResp.ProtoReflect.Descriptor instead.
func (*HomeAdvertiseDeleteResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{6}
}

func (x *HomeAdvertiseDeleteResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 添加｜｜更新优惠券
type SaveOrUpdateCouponReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type        string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name        string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Count       int64   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Amount      float32 `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	PerLimit    int64   `protobuf:"varint,7,opt,name=per_limit,json=perLimit,proto3" json:"per_limit,omitempty"`
	MinPoint    float32 `protobuf:"fixed32,8,opt,name=min_point,json=minPoint,proto3" json:"min_point,omitempty"`
	StartTime   string  `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime     string  `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	UseType     string  `protobuf:"bytes,11,opt,name=use_type,json=useType,proto3" json:"use_type,omitempty"`
	Note        string  `protobuf:"bytes,12,opt,name=note,proto3" json:"note,omitempty"`
	EnableTime  string  `protobuf:"bytes,16,opt,name=enable_time,json=enableTime,proto3" json:"enable_time,omitempty"`
	Code        string  `protobuf:"bytes,17,opt,name=code,proto3" json:"code,omitempty"`
	UseProduct  int64   `protobuf:"varint,18,opt,name=use_product,json=useProduct,proto3" json:"use_product,omitempty"`
	UseCategory int64   `protobuf:"varint,19,opt,name=use_category,json=useCategory,proto3" json:"use_category,omitempty"`
}

func (x *SaveOrUpdateCouponReq) Reset() {
	*x = SaveOrUpdateCouponReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveOrUpdateCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOrUpdateCouponReq) ProtoMessage() {}

func (x *SaveOrUpdateCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOrUpdateCouponReq.ProtoReflect.Descriptor instead.
func (*SaveOrUpdateCouponReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{7}
}

func (x *SaveOrUpdateCouponReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveOrUpdateCouponReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SaveOrUpdateCouponReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveOrUpdateCouponReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SaveOrUpdateCouponReq) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SaveOrUpdateCouponReq) GetPerLimit() int64 {
	if x != nil {
		return x.PerLimit
	}
	return 0
}

func (x *SaveOrUpdateCouponReq) GetMinPoint() float32 {
	if x != nil {
		return x.MinPoint
	}
	return 0
}

func (x *SaveOrUpdateCouponReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *SaveOrUpdateCouponReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *SaveOrUpdateCouponReq) GetUseType() string {
	if x != nil {
		return x.UseType
	}
	return ""
}

func (x *SaveOrUpdateCouponReq) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *SaveOrUpdateCouponReq) GetEnableTime() string {
	if x != nil {
		return x.EnableTime
	}
	return ""
}

func (x *SaveOrUpdateCouponReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SaveOrUpdateCouponReq) GetUseProduct() int64 {
	if x != nil {
		return x.UseProduct
	}
	return 0
}

func (x *SaveOrUpdateCouponReq) GetUseCategory() int64 {
	if x != nil {
		return x.UseCategory
	}
	return 0
}

type SaveOrUpdateCouponResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *SaveOrUpdateCouponResp) Reset() {
	*x = SaveOrUpdateCouponResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveOrUpdateCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOrUpdateCouponResp) ProtoMessage() {}

func (x *SaveOrUpdateCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOrUpdateCouponResp.ProtoReflect.Descriptor instead.
func (*SaveOrUpdateCouponResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{8}
}

func (x *SaveOrUpdateCouponResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 删除优惠券
type CouponDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *CouponDeleteReq) Reset() {
	*x = CouponDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponDeleteReq) ProtoMessage() {}

func (x *CouponDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponDeleteReq.ProtoReflect.Descriptor instead.
func (*CouponDeleteReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{9}
}

func (x *CouponDeleteReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CouponDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *CouponDeleteResp) Reset() {
	*x = CouponDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponDeleteResp) ProtoMessage() {}

func (x *CouponDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponDeleteResp.ProtoReflect.Descriptor instead.
func (*CouponDeleteResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{10}
}

func (x *CouponDeleteResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 优惠券列表
type CouponListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNum  int64  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize int64  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name     string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	UseType  string `protobuf:"bytes,8,opt,name=use_type,json=useType,proto3" json:"use_type,omitempty"`
}

func (x *CouponListReq) Reset() {
	*x = CouponListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponListReq) ProtoMessage() {}

func (x *CouponListReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponListReq.ProtoReflect.Descriptor instead.
func (*CouponListReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{11}
}

func (x *CouponListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *CouponListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CouponListReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CouponListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponListReq) GetUseType() string {
	if x != nil {
		return x.UseType
	}
	return ""
}

type CouponListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type        string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name        string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Count       int64   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Amount      float32 `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	PerLimit    int64   `protobuf:"varint,7,opt,name=per_limit,json=perLimit,proto3" json:"per_limit,omitempty"`
	MinPoint    float32 `protobuf:"fixed32,8,opt,name=min_point,json=minPoint,proto3" json:"min_point,omitempty"`
	StartTime   string  `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime     string  `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	UseType     string  `protobuf:"bytes,11,opt,name=use_type,json=useType,proto3" json:"use_type,omitempty"`
	Note        string  `protobuf:"bytes,12,opt,name=note,proto3" json:"note,omitempty"`
	EnableTime  string  `protobuf:"bytes,16,opt,name=enable_time,json=enableTime,proto3" json:"enable_time,omitempty"`
	Code        string  `protobuf:"bytes,17,opt,name=code,proto3" json:"code,omitempty"`
	UseProduct  int64   `protobuf:"varint,18,opt,name=use_product,json=useProduct,proto3" json:"use_product,omitempty"`
	UseCategory int64   `protobuf:"varint,19,opt,name=use_category,json=useCategory,proto3" json:"use_category,omitempty"`
	CreatedAt   string  `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *CouponListData) Reset() {
	*x = CouponListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponListData) ProtoMessage() {}

func (x *CouponListData) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponListData.ProtoReflect.Descriptor instead.
func (*CouponListData) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{12}
}

func (x *CouponListData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponListData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CouponListData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponListData) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CouponListData) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CouponListData) GetPerLimit() int64 {
	if x != nil {
		return x.PerLimit
	}
	return 0
}

func (x *CouponListData) GetMinPoint() float32 {
	if x != nil {
		return x.MinPoint
	}
	return 0
}

func (x *CouponListData) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CouponListData) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CouponListData) GetUseType() string {
	if x != nil {
		return x.UseType
	}
	return ""
}

func (x *CouponListData) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CouponListData) GetEnableTime() string {
	if x != nil {
		return x.EnableTime
	}
	return ""
}

func (x *CouponListData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CouponListData) GetUseProduct() int64 {
	if x != nil {
		return x.UseProduct
	}
	return 0
}

func (x *CouponListData) GetUseCategory() int64 {
	if x != nil {
		return x.UseCategory
	}
	return 0
}

func (x *CouponListData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CouponListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64             `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*CouponListData `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *CouponListResp) Reset() {
	*x = CouponListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CouponListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponListResp) ProtoMessage() {}

func (x *CouponListResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponListResp.ProtoReflect.Descriptor instead.
func (*CouponListResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{13}
}

func (x *CouponListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CouponListResp) GetList() []*CouponListData {
	if x != nil {
		return x.List
	}
	return nil
}

// 添加专题
type SaveOrUpdateSubjectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pic    string `protobuf:"bytes,3,opt,name=pic,proto3" json:"pic,omitempty"`
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Sort   int64  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (x *SaveOrUpdateSubjectReq) Reset() {
	*x = SaveOrUpdateSubjectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveOrUpdateSubjectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOrUpdateSubjectReq) ProtoMessage() {}

func (x *SaveOrUpdateSubjectReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOrUpdateSubjectReq.ProtoReflect.Descriptor instead.
func (*SaveOrUpdateSubjectReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{14}
}

func (x *SaveOrUpdateSubjectReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveOrUpdateSubjectReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveOrUpdateSubjectReq) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *SaveOrUpdateSubjectReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SaveOrUpdateSubjectReq) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type SaveOrUpdateSubjectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *SaveOrUpdateSubjectResp) Reset() {
	*x = SaveOrUpdateSubjectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveOrUpdateSubjectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOrUpdateSubjectResp) ProtoMessage() {}

func (x *SaveOrUpdateSubjectResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOrUpdateSubjectResp.ProtoReflect.Descriptor instead.
func (*SaveOrUpdateSubjectResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{15}
}

func (x *SaveOrUpdateSubjectResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 删除专题
type SubjectDeleteAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *SubjectDeleteAddReq) Reset() {
	*x = SubjectDeleteAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectDeleteAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectDeleteAddReq) ProtoMessage() {}

func (x *SubjectDeleteAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectDeleteAddReq.ProtoReflect.Descriptor instead.
func (*SubjectDeleteAddReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{16}
}

func (x *SubjectDeleteAddReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type SubjectDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *SubjectDeleteResp) Reset() {
	*x = SubjectDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectDeleteResp) ProtoMessage() {}

func (x *SubjectDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectDeleteResp.ProtoReflect.Descriptor instead.
func (*SubjectDeleteResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{17}
}

func (x *SubjectDeleteResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 专题列表
type SubjectListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNum  int64  `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize int64  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status   string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Name     string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SubjectListReq) Reset() {
	*x = SubjectListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectListReq) ProtoMessage() {}

func (x *SubjectListReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectListReq.ProtoReflect.Descriptor instead.
func (*SubjectListReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{18}
}

func (x *SubjectListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *SubjectListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SubjectListReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubjectListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SubjectListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pic       string `protobuf:"bytes,3,opt,name=pic,proto3" json:"pic,omitempty"`
	Status    string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Sort      int64  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	CreatedAt string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *SubjectListData) Reset() {
	*x = SubjectListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectListData) ProtoMessage() {}

func (x *SubjectListData) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectListData.ProtoReflect.Descriptor instead.
func (*SubjectListData) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{19}
}

func (x *SubjectListData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubjectListData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubjectListData) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *SubjectListData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubjectListData) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *SubjectListData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SubjectListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*SubjectListData `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SubjectListResp) Reset() {
	*x = SubjectListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectListResp) ProtoMessage() {}

func (x *SubjectListResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectListResp.ProtoReflect.Descriptor instead.
func (*SubjectListResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{20}
}

func (x *SubjectListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SubjectListResp) GetList() []*SubjectListData {
	if x != nil {
		return x.List
	}
	return nil
}

// SaveOrUpdateSubjectProduct 添加｜｜更新专题商品
type SaveOrUpdateSubjectProductReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectId int64   `protobuf:"varint,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Sort      int64   `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	ProductId []int64 `protobuf:"varint,4,rep,packed,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *SaveOrUpdateSubjectProductReq) Reset() {
	*x = SaveOrUpdateSubjectProductReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveOrUpdateSubjectProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOrUpdateSubjectProductReq) ProtoMessage() {}

func (x *SaveOrUpdateSubjectProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOrUpdateSubjectProductReq.ProtoReflect.Descriptor instead.
func (*SaveOrUpdateSubjectProductReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{21}
}

func (x *SaveOrUpdateSubjectProductReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveOrUpdateSubjectProductReq) GetSubjectId() int64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *SaveOrUpdateSubjectProductReq) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *SaveOrUpdateSubjectProductReq) GetProductId() []int64 {
	if x != nil {
		return x.ProductId
	}
	return nil
}

type SaveOrUpdateSubjectProductResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *SaveOrUpdateSubjectProductResp) Reset() {
	*x = SaveOrUpdateSubjectProductResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveOrUpdateSubjectProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveOrUpdateSubjectProductResp) ProtoMessage() {}

func (x *SaveOrUpdateSubjectProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveOrUpdateSubjectProductResp.ProtoReflect.Descriptor instead.
func (*SaveOrUpdateSubjectProductResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{22}
}

func (x *SaveOrUpdateSubjectProductResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 删除专题商品
type SubjectProductDeleteAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDs []int64 `protobuf:"varint,1,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
}

func (x *SubjectProductDeleteAddReq) Reset() {
	*x = SubjectProductDeleteAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectProductDeleteAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectProductDeleteAddReq) ProtoMessage() {}

func (x *SubjectProductDeleteAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectProductDeleteAddReq.ProtoReflect.Descriptor instead.
func (*SubjectProductDeleteAddReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{23}
}

func (x *SubjectProductDeleteAddReq) GetIDs() []int64 {
	if x != nil {
		return x.IDs
	}
	return nil
}

type SubjectProductDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *SubjectProductDeleteResp) Reset() {
	*x = SubjectProductDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectProductDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectProductDeleteResp) ProtoMessage() {}

func (x *SubjectProductDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectProductDeleteResp.ProtoReflect.Descriptor instead.
func (*SubjectProductDeleteResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{24}
}

func (x *SubjectProductDeleteResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// 专题列表商品
type SubjectProductListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNum   int64 `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize  int64 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SubjectId int64 `protobuf:"varint,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
}

func (x *SubjectProductListReq) Reset() {
	*x = SubjectProductListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectProductListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectProductListReq) ProtoMessage() {}

func (x *SubjectProductListReq) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectProductListReq.ProtoReflect.Descriptor instead.
func (*SubjectProductListReq) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{25}
}

func (x *SubjectProductListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *SubjectProductListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SubjectProductListReq) GetSubjectId() int64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

type SubjectProductListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 int64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectId          int64               `protobuf:"varint,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	ProductId          int64               `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sort               int64               `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`
	SubjectProductInfo *SubjectProductInfo `protobuf:"bytes,6,opt,name=subject_product_info,json=subjectProductInfo,proto3" json:"subject_product_info,omitempty"`
}

func (x *SubjectProductListData) Reset() {
	*x = SubjectProductListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectProductListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectProductListData) ProtoMessage() {}

func (x *SubjectProductListData) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectProductListData.ProtoReflect.Descriptor instead.
func (*SubjectProductListData) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{26}
}

func (x *SubjectProductListData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubjectProductListData) GetSubjectId() int64 {
	if x != nil {
		return x.SubjectId
	}
	return 0
}

func (x *SubjectProductListData) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SubjectProductListData) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *SubjectProductListData) GetSubjectProductInfo() *SubjectProductInfo {
	if x != nil {
		return x.SubjectProductInfo
	}
	return nil
}

type SubjectProductInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pic       string  `protobuf:"bytes,2,opt,name=pic,proto3" json:"pic,omitempty"`
	ProductSn string  `protobuf:"bytes,3,opt,name=product_sn,json=productSn,proto3" json:"product_sn,omitempty"`
	Desc      string  `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Price     float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *SubjectProductInfo) Reset() {
	*x = SubjectProductInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectProductInfo) ProtoMessage() {}

func (x *SubjectProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectProductInfo.ProtoReflect.Descriptor instead.
func (*SubjectProductInfo) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{27}
}

func (x *SubjectProductInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubjectProductInfo) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *SubjectProductInfo) GetProductSn() string {
	if x != nil {
		return x.ProductSn
	}
	return ""
}

func (x *SubjectProductInfo) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *SubjectProductInfo) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type SubjectProductListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64                     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*SubjectProductListData `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *SubjectProductListResp) Reset() {
	*x = SubjectProductListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectProductListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectProductListResp) ProtoMessage() {}

func (x *SubjectProductListResp) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectProductListResp.ProtoReflect.Descriptor instead.
func (*SubjectProductListResp) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{28}
}

func (x *SubjectProductListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SubjectProductListResp) GetList() []*SubjectProductListData {
	if x != nil {
		return x.List
	}
	return nil
}

var File_sms_proto protoreflect.FileDescriptor

var file_sms_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x6d, 0x73,
	0x22, 0xa6, 0x01, 0x0a, 0x1c, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73,
	0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0x33, 0x0a, 0x1d, 0x53, 0x61, 0x76,
	0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64, 0x76,
	0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x7a,
	0x0a, 0x14, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75,
	0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xbe, 0x01, 0x0a, 0x15, 0x48,
	0x6f, 0x6d, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x5d, 0x0a, 0x15, 0x48,
	0x6f, 0x6d, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x48,
	0x6f, 0x6d, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x16, 0x48, 0x6f,
	0x6d, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x2d, 0x0a, 0x17, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x99, 0x03, 0x0a, 0x15, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x65, 0x72, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x75, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x12, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x75, 0x73, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x13,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x22, 0x2c, 0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22,
	0x23, 0x0a, 0x0f, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x03, 0x69, 0x64, 0x73, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x8a, 0x01, 0x0a,
	0x0d, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x75, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0xb1, 0x03, 0x0a, 0x0e, 0x43, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x11,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x12, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x75, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x75,
	0x73, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x13, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x14, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x4f, 0x0a,
	0x0e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x7a,
	0x0a, 0x16, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x2d, 0x0a, 0x17, 0x53, 0x61,
	0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x27, 0x0a, 0x13, 0x53, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x69,
	0x64, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x74, 0x0a, 0x0e, 0x53,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x92, 0x01, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x51, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x28, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x73, 0x6d, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x1d, 0x53, 0x61,
	0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x22, 0x34, 0x0a,
	0x1e, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x6f, 0x6e, 0x67, 0x22, 0x2e, 0x0a, 0x1a, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03,
	0x49, 0x44, 0x73, 0x22, 0x2e, 0x0a, 0x18, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x6f, 0x6e, 0x67, 0x22, 0x6e, 0x0a, 0x15, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x22, 0xc5, 0x01, 0x0a, 0x16, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x12, 0x49, 0x0a, 0x14, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x12, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x12,
	0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x73, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x22, 0x5f, 0x0a, 0x16, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x2f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x32, 0xa7, 0x07, 0x0a, 0x03, 0x53, 0x6d, 0x73, 0x12, 0x62, 0x0a, 0x19, 0x53, 0x61,
	0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x12, 0x21, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x61,
	0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x73, 0x6d, 0x73,
	0x2e, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x6d,
	0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4a,
	0x0a, 0x11, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x50, 0x0a, 0x13, 0x48, 0x6f,
	0x6d, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x1b, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64, 0x76, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c,
	0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4d, 0x0a, 0x12,
	0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1b,
	0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0c, 0x43,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x73, 0x6d,
	0x73, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0a, 0x43, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x73, 0x6d, 0x73,
	0x2e, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x50, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x61, 0x76,
	0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x41, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x73,
	0x6d, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x65,
	0x0a, 0x1a, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x22, 0x2e, 0x73,
	0x6d, 0x73, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x23, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x56, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1f, 0x2e,
	0x73, 0x6d, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1d,
	0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4d, 0x0a,
	0x12, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x73, 0x6d, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x73, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sms_proto_rawDescOnce sync.Once
	file_sms_proto_rawDescData = file_sms_proto_rawDesc
)

func file_sms_proto_rawDescGZIP() []byte {
	file_sms_proto_rawDescOnce.Do(func() {
		file_sms_proto_rawDescData = protoimpl.X.CompressGZIP(file_sms_proto_rawDescData)
	})
	return file_sms_proto_rawDescData
}

var file_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_sms_proto_goTypes = []interface{}{
	(*SaveOrUpdateHomeAdvertiseReq)(nil),   // 0: sms.SaveOrUpdateHomeAdvertiseReq
	(*SaveOrUpdateHomeAdvertiseResp)(nil),  // 1: sms.SaveOrUpdateHomeAdvertiseResp
	(*HomeAdvertiseListReq)(nil),           // 2: sms.HomeAdvertiseListReq
	(*HomeAdvertiseListData)(nil),          // 3: sms.HomeAdvertiseListData
	(*HomeAdvertiseListResp)(nil),          // 4: sms.HomeAdvertiseListResp
	(*HomeAdvertiseDeleteReq)(nil),         // 5: sms.HomeAdvertiseDeleteReq
	(*HomeAdvertiseDeleteResp)(nil),        // 6: sms.HomeAdvertiseDeleteResp
	(*SaveOrUpdateCouponReq)(nil),          // 7: sms.SaveOrUpdateCouponReq
	(*SaveOrUpdateCouponResp)(nil),         // 8: sms.SaveOrUpdateCouponResp
	(*CouponDeleteReq)(nil),                // 9: sms.CouponDeleteReq
	(*CouponDeleteResp)(nil),               // 10: sms.CouponDeleteResp
	(*CouponListReq)(nil),                  // 11: sms.CouponListReq
	(*CouponListData)(nil),                 // 12: sms.CouponListData
	(*CouponListResp)(nil),                 // 13: sms.CouponListResp
	(*SaveOrUpdateSubjectReq)(nil),         // 14: sms.SaveOrUpdateSubjectReq
	(*SaveOrUpdateSubjectResp)(nil),        // 15: sms.SaveOrUpdateSubjectResp
	(*SubjectDeleteAddReq)(nil),            // 16: sms.SubjectDeleteAddReq
	(*SubjectDeleteResp)(nil),              // 17: sms.SubjectDeleteResp
	(*SubjectListReq)(nil),                 // 18: sms.SubjectListReq
	(*SubjectListData)(nil),                // 19: sms.SubjectListData
	(*SubjectListResp)(nil),                // 20: sms.SubjectListResp
	(*SaveOrUpdateSubjectProductReq)(nil),  // 21: sms.SaveOrUpdateSubjectProductReq
	(*SaveOrUpdateSubjectProductResp)(nil), // 22: sms.SaveOrUpdateSubjectProductResp
	(*SubjectProductDeleteAddReq)(nil),     // 23: sms.SubjectProductDeleteAddReq
	(*SubjectProductDeleteResp)(nil),       // 24: sms.SubjectProductDeleteResp
	(*SubjectProductListReq)(nil),          // 25: sms.SubjectProductListReq
	(*SubjectProductListData)(nil),         // 26: sms.SubjectProductListData
	(*SubjectProductInfo)(nil),             // 27: sms.SubjectProductInfo
	(*SubjectProductListResp)(nil),         // 28: sms.SubjectProductListResp
}
var file_sms_proto_depIdxs = []int32{
	3,  // 0: sms.HomeAdvertiseListResp.list:type_name -> sms.HomeAdvertiseListData
	12, // 1: sms.CouponListResp.list:type_name -> sms.CouponListData
	19, // 2: sms.SubjectListResp.list:type_name -> sms.SubjectListData
	27, // 3: sms.SubjectProductListData.subject_product_info:type_name -> sms.SubjectProductInfo
	26, // 4: sms.SubjectProductListResp.list:type_name -> sms.SubjectProductListData
	0,  // 5: sms.Sms.SaveOrUpdateHomeAdvertise:input_type -> sms.SaveOrUpdateHomeAdvertiseReq
	2,  // 6: sms.Sms.HomeAdvertiseList:input_type -> sms.HomeAdvertiseListReq
	5,  // 7: sms.Sms.HomeAdvertiseDelete:input_type -> sms.HomeAdvertiseDeleteReq
	7,  // 8: sms.Sms.SaveOrUpdateCoupon:input_type -> sms.SaveOrUpdateCouponReq
	9,  // 9: sms.Sms.CouponDelete:input_type -> sms.CouponDeleteReq
	11, // 10: sms.Sms.CouponList:input_type -> sms.CouponListReq
	14, // 11: sms.Sms.SaveOrUpdateSubject:input_type -> sms.SaveOrUpdateSubjectReq
	16, // 12: sms.Sms.SubjectDelete:input_type -> sms.SubjectDeleteAddReq
	18, // 13: sms.Sms.SubjectList:input_type -> sms.SubjectListReq
	21, // 14: sms.Sms.SaveOrUpdateSubjectProduct:input_type -> sms.SaveOrUpdateSubjectProductReq
	23, // 15: sms.Sms.SubjectProductDelete:input_type -> sms.SubjectProductDeleteAddReq
	25, // 16: sms.Sms.SubjectProductList:input_type -> sms.SubjectProductListReq
	1,  // 17: sms.Sms.SaveOrUpdateHomeAdvertise:output_type -> sms.SaveOrUpdateHomeAdvertiseResp
	4,  // 18: sms.Sms.HomeAdvertiseList:output_type -> sms.HomeAdvertiseListResp
	6,  // 19: sms.Sms.HomeAdvertiseDelete:output_type -> sms.HomeAdvertiseDeleteResp
	8,  // 20: sms.Sms.SaveOrUpdateCoupon:output_type -> sms.SaveOrUpdateCouponResp
	10, // 21: sms.Sms.CouponDelete:output_type -> sms.CouponDeleteResp
	13, // 22: sms.Sms.CouponList:output_type -> sms.CouponListResp
	15, // 23: sms.Sms.SaveOrUpdateSubject:output_type -> sms.SaveOrUpdateSubjectResp
	17, // 24: sms.Sms.SubjectDelete:output_type -> sms.SubjectDeleteResp
	20, // 25: sms.Sms.SubjectList:output_type -> sms.SubjectListResp
	22, // 26: sms.Sms.SaveOrUpdateSubjectProduct:output_type -> sms.SaveOrUpdateSubjectProductResp
	24, // 27: sms.Sms.SubjectProductDelete:output_type -> sms.SubjectProductDeleteResp
	28, // 28: sms.Sms.SubjectProductList:output_type -> sms.SubjectProductListResp
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sms_proto_init() }
func file_sms_proto_init() {
	if File_sms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveOrUpdateHomeAdvertiseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveOrUpdateHomeAdvertiseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeAdvertiseListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeAdvertiseListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeAdvertiseListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeAdvertiseDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HomeAdvertiseDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveOrUpdateCouponReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveOrUpdateCouponResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CouponListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveOrUpdateSubjectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveOrUpdateSubjectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectDeleteAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveOrUpdateSubjectProductReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveOrUpdateSubjectProductResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectProductDeleteAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectProductDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectProductListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectProductListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectProductInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sms_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubjectProductListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sms_proto_goTypes,
		DependencyIndexes: file_sms_proto_depIdxs,
		MessageInfos:      file_sms_proto_msgTypes,
	}.Build()
	File_sms_proto = out.File
	file_sms_proto_rawDesc = nil
	file_sms_proto_goTypes = nil
	file_sms_proto_depIdxs = nil
}
