// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: sms.proto

package sms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Sms_SaveOrUpdateHomeAdvertise_FullMethodName = "/sms.Sms/SaveOrUpdateHomeAdvertise"
	Sms_HomeAdvertiseList_FullMethodName         = "/sms.Sms/HomeAdvertiseList"
	Sms_HomeAdvertiseDelete_FullMethodName       = "/sms.Sms/HomeAdvertiseDelete"
	Sms_SaveOrUpdateCoupon_FullMethodName        = "/sms.Sms/SaveOrUpdateCoupon"
	Sms_CouponDelete_FullMethodName              = "/sms.Sms/CouponDelete"
	Sms_CouponList_FullMethodName                = "/sms.Sms/CouponList"
)

// SmsClient is the client API for Sms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmsClient interface {
	// 添加｜｜更新广告
	SaveOrUpdateHomeAdvertise(ctx context.Context, in *SaveOrUpdateHomeAdvertiseReq, opts ...grpc.CallOption) (*SaveOrUpdateHomeAdvertiseResp, error)
	// 广告列表
	HomeAdvertiseList(ctx context.Context, in *HomeAdvertiseListReq, opts ...grpc.CallOption) (*HomeAdvertiseListResp, error)
	// 删除广告
	HomeAdvertiseDelete(ctx context.Context, in *HomeAdvertiseDeleteReq, opts ...grpc.CallOption) (*HomeAdvertiseDeleteResp, error)
	// 添加｜｜更新优惠券
	SaveOrUpdateCoupon(ctx context.Context, in *SaveOrUpdateCouponReq, opts ...grpc.CallOption) (*SaveOrUpdateCouponResp, error)
	// 删除优惠券
	CouponDelete(ctx context.Context, in *CouponDeleteReq, opts ...grpc.CallOption) (*CouponDeleteResp, error)
	// 优惠券列表
	CouponList(ctx context.Context, in *CouponListReq, opts ...grpc.CallOption) (*CouponListResp, error)
}

type smsClient struct {
	cc grpc.ClientConnInterface
}

func NewSmsClient(cc grpc.ClientConnInterface) SmsClient {
	return &smsClient{cc}
}

func (c *smsClient) SaveOrUpdateHomeAdvertise(ctx context.Context, in *SaveOrUpdateHomeAdvertiseReq, opts ...grpc.CallOption) (*SaveOrUpdateHomeAdvertiseResp, error) {
	out := new(SaveOrUpdateHomeAdvertiseResp)
	err := c.cc.Invoke(ctx, Sms_SaveOrUpdateHomeAdvertise_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeAdvertiseList(ctx context.Context, in *HomeAdvertiseListReq, opts ...grpc.CallOption) (*HomeAdvertiseListResp, error) {
	out := new(HomeAdvertiseListResp)
	err := c.cc.Invoke(ctx, Sms_HomeAdvertiseList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) HomeAdvertiseDelete(ctx context.Context, in *HomeAdvertiseDeleteReq, opts ...grpc.CallOption) (*HomeAdvertiseDeleteResp, error) {
	out := new(HomeAdvertiseDeleteResp)
	err := c.cc.Invoke(ctx, Sms_HomeAdvertiseDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) SaveOrUpdateCoupon(ctx context.Context, in *SaveOrUpdateCouponReq, opts ...grpc.CallOption) (*SaveOrUpdateCouponResp, error) {
	out := new(SaveOrUpdateCouponResp)
	err := c.cc.Invoke(ctx, Sms_SaveOrUpdateCoupon_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponDelete(ctx context.Context, in *CouponDeleteReq, opts ...grpc.CallOption) (*CouponDeleteResp, error) {
	out := new(CouponDeleteResp)
	err := c.cc.Invoke(ctx, Sms_CouponDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) CouponList(ctx context.Context, in *CouponListReq, opts ...grpc.CallOption) (*CouponListResp, error) {
	out := new(CouponListResp)
	err := c.cc.Invoke(ctx, Sms_CouponList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsServer is the server API for Sms service.
// All implementations must embed UnimplementedSmsServer
// for forward compatibility
type SmsServer interface {
	// 添加｜｜更新广告
	SaveOrUpdateHomeAdvertise(context.Context, *SaveOrUpdateHomeAdvertiseReq) (*SaveOrUpdateHomeAdvertiseResp, error)
	// 广告列表
	HomeAdvertiseList(context.Context, *HomeAdvertiseListReq) (*HomeAdvertiseListResp, error)
	// 删除广告
	HomeAdvertiseDelete(context.Context, *HomeAdvertiseDeleteReq) (*HomeAdvertiseDeleteResp, error)
	// 添加｜｜更新优惠券
	SaveOrUpdateCoupon(context.Context, *SaveOrUpdateCouponReq) (*SaveOrUpdateCouponResp, error)
	// 删除优惠券
	CouponDelete(context.Context, *CouponDeleteReq) (*CouponDeleteResp, error)
	// 优惠券列表
	CouponList(context.Context, *CouponListReq) (*CouponListResp, error)
	mustEmbedUnimplementedSmsServer()
}

// UnimplementedSmsServer must be embedded to have forward compatible implementations.
type UnimplementedSmsServer struct {
}

func (UnimplementedSmsServer) SaveOrUpdateHomeAdvertise(context.Context, *SaveOrUpdateHomeAdvertiseReq) (*SaveOrUpdateHomeAdvertiseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveOrUpdateHomeAdvertise not implemented")
}
func (UnimplementedSmsServer) HomeAdvertiseList(context.Context, *HomeAdvertiseListReq) (*HomeAdvertiseListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeAdvertiseList not implemented")
}
func (UnimplementedSmsServer) HomeAdvertiseDelete(context.Context, *HomeAdvertiseDeleteReq) (*HomeAdvertiseDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomeAdvertiseDelete not implemented")
}
func (UnimplementedSmsServer) SaveOrUpdateCoupon(context.Context, *SaveOrUpdateCouponReq) (*SaveOrUpdateCouponResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveOrUpdateCoupon not implemented")
}
func (UnimplementedSmsServer) CouponDelete(context.Context, *CouponDeleteReq) (*CouponDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponDelete not implemented")
}
func (UnimplementedSmsServer) CouponList(context.Context, *CouponListReq) (*CouponListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CouponList not implemented")
}
func (UnimplementedSmsServer) mustEmbedUnimplementedSmsServer() {}

// UnsafeSmsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmsServer will
// result in compilation errors.
type UnsafeSmsServer interface {
	mustEmbedUnimplementedSmsServer()
}

func RegisterSmsServer(s grpc.ServiceRegistrar, srv SmsServer) {
	s.RegisterService(&Sms_ServiceDesc, srv)
}

func _Sms_SaveOrUpdateHomeAdvertise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveOrUpdateHomeAdvertiseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).SaveOrUpdateHomeAdvertise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_SaveOrUpdateHomeAdvertise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).SaveOrUpdateHomeAdvertise(ctx, req.(*SaveOrUpdateHomeAdvertiseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeAdvertiseList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeAdvertiseListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeAdvertiseList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_HomeAdvertiseList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeAdvertiseList(ctx, req.(*HomeAdvertiseListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_HomeAdvertiseDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeAdvertiseDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).HomeAdvertiseDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_HomeAdvertiseDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).HomeAdvertiseDelete(ctx, req.(*HomeAdvertiseDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_SaveOrUpdateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveOrUpdateCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).SaveOrUpdateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_SaveOrUpdateCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).SaveOrUpdateCoupon(ctx, req.(*SaveOrUpdateCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_CouponDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponDelete(ctx, req.(*CouponDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_CouponList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CouponListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).CouponList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sms_CouponList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).CouponList(ctx, req.(*CouponListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Sms_ServiceDesc is the grpc.ServiceDesc for Sms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sms.Sms",
	HandlerType: (*SmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveOrUpdateHomeAdvertise",
			Handler:    _Sms_SaveOrUpdateHomeAdvertise_Handler,
		},
		{
			MethodName: "HomeAdvertiseList",
			Handler:    _Sms_HomeAdvertiseList_Handler,
		},
		{
			MethodName: "HomeAdvertiseDelete",
			Handler:    _Sms_HomeAdvertiseDelete_Handler,
		},
		{
			MethodName: "SaveOrUpdateCoupon",
			Handler:    _Sms_SaveOrUpdateCoupon_Handler,
		},
		{
			MethodName: "CouponDelete",
			Handler:    _Sms_CouponDelete_Handler,
		},
		{
			MethodName: "CouponList",
			Handler:    _Sms_CouponList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sms.proto",
}
